parameters:
#    mero_base.example.class: Mero\BaseBundle\Example

services:
#    mero_base.example:
#        class: %mero_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
